POST http://localhost:8080/article
Content-Type: application/json

{
  "title": "title1",
  "content": "content1"
}

###
GET http://localhost:8080/article
Accept: application/json


###
GET http://localhost:8080/article/1
Accept: application/json

###
DELETE http://localhost:8080/article/1




